---
abstract: 'Run-time load a class the first time you call a method in it.'
author:
  - 'Adam Kennedy <cpan@ali.as>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Temp: 0.17
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Class::Autouse
name: Class-Autouse
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  File::Spec: 0.80
  List::Util: 1.19
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Class-Autouse
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Class-Autouse
version: 2.00
