
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 1.26
name: Class-Autouse
author: Adam Kennedy (Creator and Maintainer), L<http://ali.as/>, cpan@ali.as
license: perl
build_requires: 
  Test::More: 0.47
requires: 
  List::Util: 1.18
  base: 0
  perl: 5.005
  File::Spec: 0.80
  Carp: 0
abstract: Run-time load a class the first time you call a method in it.
