name: Class-Autouse
version: 1.22
abstract: Run-time class loading on first method call
author: Adam Kennedy (Creator and Maintainer), L<http://ali.as/>, cpan@ali.as
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
requires:
  perl: 5.005
  Carp: 0
  File::Spec: 0.80
  List::Util: 1.11
no_index:
  directory:
    - t
    - inc
generated_by: Module::Install version 0.45
