name: Class-Autouse
version: 1.15
abstract: Run-time class loading on first method call
author: Adam Kennedy<cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
requires:
  perl: 5.005
  Carp: 0
  File::Spec: 0.82
  List::Util: 1.11
no_index:
  directory:
    - modules
    - inc
generated_by: Module::Install version 0.36
