name:         Class-Autouse
version:      1.03
version_from: lib/Class/Autouse.pm
installdirs:  site
license:      perl
requires:
  perl:                          5.005
  Carp:                          0
  File::Spec:                    0.82
  List::Util:                    0
build_requires:
  Test::More:                    0
private:
  directory:
    - modules
distribution_type: module
generated_by: hand
