--- 
abstract: Run-time load a class the first time you call a method in it.
author: 
  - Adam Kennedy <cpan@ali.as>
build_requires: 
  File::Temp: 0
  Test::More: 0.47
  base: 0
distribution_type: module
generated_by: Module::Install version 0.680
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Class-Autouse
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  File::Spec: 0.80
  List::Util: 1.19
  constant: 0
  lib: 0
  perl: 5.005
version: 1.99_01
